[package]
name = "flights-overhead"
version = "0.1.0"
authors = ["Tom Milligan <tommilligan@users.noreply.github.com>"]

[dependencies]
clap = "2.32.0"
reqwest = "0.9.5"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
termion = "1.5.1"

